### ISSUE TITLE
Get travis and codacy to run tests

### ISSUE THREAD

**Issue by mariobehling** [fossasia/Pocket-Science-Lab#85]
I have connected the app with travis and codacy, but it is not running out of the box. Please help to make it work.

**Comment by wavicles** [comment]
@mariobehling 
Updated .travis.yml
We do not have setup.py and requirements.txt files in the repo. Therefore removed those lines.
Travis build is passed. Now I will work on the bugs reported by @georgesk 

Thanks a lot.
